language: node_js
node_js:
- '10'
branches:
  only:
  - src
before_install:
- openssl aes-256-cbc -K $encrypted_6b5b110e1eb2_key -iv $encrypted_6b5b110e1eb2_iv -in __config.yml.enc -out _config.yml -d
install:
- npm install -g hexo-cli
- npm install -g hexo
after_install:
- hexo -v
script:
- hexo clean
- hexo g
- mv ./other/* ./public
- rm -rf other/
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "${GITHUB_TOKEN}"
    keep_history: true
    local_dir: "./public/"
    target_branch: master
    on:
      branch: src
  - provider: script
    script: bash deploy.sh
    on:
      branch: src
after_deploy:
- hexo d